version: '3'

services:
   mysql:
     build: . #Dockerfileからビルド
     image: mysql:5.7 #imageの名前
     container_name: 'mysql-data'
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 'root'
       MYSQL_DATABASE: 'mysql'
       MYSQL_USER: 'mysql'
       MYSQL_PASSWORD: 'mysql'
     ports:
       - "4306:3306"

volumes:
    db_data:
